services:
  customers-api:
    build: ./customers-api
    container_name: customers_api
    ports:
      - "3001:3001"
    env_file:
      - ./customers-api/.env

  orders-api:
    build: ./orders-api
    container_name: orders_api
    ports:
      - "3002:3002"
    env_file:
      - ./orders-api/.env
    depends_on:
      - customers-api
