version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: b2b
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/2_seed.sql

  customers-api:
    build: ./customers-api
    container_name: customers_api
    ports:
      - "3001:3001"
    env_file:
      - ./customers-api/.env
    depends_on:
      - mysql

  orders-api:
    build: ./orders-api
    container_name: orders_api
    ports:
      - "3002:3002"
    env_file:
      - ./orders-api/.env
    depends_on:
      - mysql
      - customers-api
