service: lambda-orchestrator
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  timeout: 15
  httpApi:
    cors: true
  environment:
    CUSTOMERS_API_BASE: ${env:CUSTOMERS_API_BASE}
    ORDERS_API_BASE: ${env:ORDERS_API_BASE}
    SERVICE_TOKEN: ${env:SERVICE_TOKEN}
    JWT_TOKEN_FOR_APIS: ${env:JWT_TOKEN_FOR_APIS}

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3003
    lambdaPort: 4000
    noPrependStageInUrl: true

functions:
  orchestrator:
    handler: handler.createAndConfirm
    events:
      - httpApi:
          path: /orchestrator/create-and-confirm-order
          method: post
