service: lambda-orchestrator
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    CUSTOMERS_API_BASE: ${env:CUSTOMERS_API_BASE}
    ORDERS_API_BASE: ${env:ORDERS_API_BASE}
    SERVICE_TOKEN: ${env:SERVICE_TOKEN}
    JWT_TOKEN_FOR_APIS: ${env:JWT_TOKEN_FOR_APIS}

plugins:
  - serverless-offline

functions:
  orchestrator:
    handler: handler.createAndConfirm
    events:
      - httpApi:
          path: /orchestrator/create-and-confirm-order
          method: post
          cors: true
